### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by BlackBird1127**
Initial Front end

# Preliminary Info

1. Connected issue ticket: [IKCE-002 Frontend Information Architecture [EPIC] #3](https://github.com/IKC-Reporting/IKC_Frontend/issues/3)
2. Goal of merge request:
   - This PR is for the creation of the initial front end architecture
3. Potential areas of concern/Issues
   - This may be limited by x.
   - This could cause issues with y.

# Testing

System testing

## Unit Tests

**run `npm run coverage` and screenshots any changed files.**

### Coverage report screenshot

**run `npm run coverage` and screenshot the final output. (ex x of y covered)**

image

## Security Tests

**screenshots of security test output from `snyk test` and `snyk code test`.**

## Examples

**screenshot or screen-record any changes to the UI for altered components/css, or demo of any major functional changes.**

### CODE REVIEW

**Comment by anthonysasso2001** [comment]
Can you update the description just to give some context, may also be recommended to make this a draft PR if work is still being done

**Review by Mjovanovic3875 — DISMISSED** [review]
Initial web page creation.

**Review by anthonysasso2001 — DISMISSED** [review]

**Comment by Mjovanovic3875** [comment]
added coverage test pass

**Comment by anthonysasso2001** [comment]
work split into different PRs, this is no longer up to date

**Pull request closed without merging**
